//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jaja_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_1
    {
        public int id { get; set; }
        
        public string clearance_branch { get; set; }
        public string date { get; set; }
        public string valid_id { get; set; }
        public string complete_name { get; set; }
        public string husband_surname { get; set; }
        public string nickname { get; set; }
        public string other_name { get; set; }
        public string present_address { get; set; }
        public string date_of_birth { get; set; }
        public string place_of_birth { get; set; }
        public string educ_attainment { get; set; }
        public string contact_no { get; set; }
        public string email { get; set; }
        public string gender { get; set; }
        public string citizenship { get; set; }
        public string complexion { get; set; }
        public string scar_marks { get; set; }
        public string religion { get; set; }
        public string height { get; set; }
        public string weight { get; set; }
        public string spouse_name { get; set; }
        public string father_name { get; set; }
        public string father_birthplace { get; set; }
        public string mother_name { get; set; }
        public string mother_birthplace { get; set; }
    }
}
